version: 2
jobs:
  test:
    docker:
      - image: cimg/node:18.15
    steps:
      # - add_ssh_keys:
      #     fingerprints:
      #       - "68:4b:af:b0:a6:5e:d6:59:a1:ee:bf:12:36:9d:7d:fc"
      - checkout
      - run: yarn install --frozen-lockfile
      - run: yarn lint
      - run: yarn test
  do_release:
    docker:
      - image: cimg/node:18.15
    steps:
      # - add_ssh_keys:
      #     fingerprints:
      #       - "68:4b:af:b0:a6:5e:d6:59:a1:ee:bf:12:36:9d:7d:fc"
      - checkout
      - run:
          command: |
            COMMIT_MSG=$(git log --format=oneline -n 1 $CIRCLE_SHA1)
            if [[ $COMMIT_MSG == *"[skip-ci-version]"* ]]; then
              echo "[skip-ci-version] detected. Stopping."
              circleci step halt
            fi
      - run: yarn install --frozen-lockfile
      - run: yarn run build
      - run: git config --global user.email "$GIT_AUTHOR_EMAIL"
      - run: git config --global user.name "$GIT_AUTHOR_NAME"
      - run: yarn run release
workflows:
  version: 2
  do_build:
    jobs:
      - test:
          context: public_package_publish
      - do_release:
          # requires:
          #   - test
          context: public_package_publish
          filters:
            branches:
              only:
                - master
                - alpha
                - qa
                - dev
                - /prerelease\/.*/